Completed Typescript Conditionals Exercise-Allyson Greven
allygreven/c1024-code-solutions pull request #11
Opened 2024-10-24 23:21 UTC by allygreven

![Screenshot 2024-10-24 at 4 17 34 PM (2)](https://github.com/user-attachments/assets/ccfa8381-2648-40fe-893e-d61066a157e9)

2024-10-25 15:43 UTC, shawnkost requested changes
A few changes here Ally!

2024-10-25 15:43 UTC, shawnkost commented on typescript-conditionals/main.ts
> +}
This isn't accounting for even numbers, this is just checking if `number` is greater than or equal to 4. You should be utilizing the `%` operator, to check if a number is even or odd

2024-10-25 15:43 UTC, shawnkost commented on typescript-conditionals/main.ts
> +    return 'acid';
Are all numbers less than 0 considered acid? What about negative numbers?

2024-10-25 15:43 UTC, shawnkost commented on typescript-conditionals/main.ts
> +    return 'base';
What about 14? Is 14 not considered a base?

2024-10-25 19:20 UTC, allygreven commented
![Screenshot 2024-10-25 at 12 18 13 PM (2)](https://github.com/user-attachments/assets/485c217c-876f-48a2-ac38-ab4f8030e495)

2024-10-29 15:25 UTC, shawnkost approved these changes
👍🏻

2024-10-29 15:43 UTC, merged