Completed Typescript Forms Exercise-Allyson Greven
allygreven/c1024-code-solutions pull request #45
Opened 2024-11-07 20:00 UTC by allygreven

![Screenshot 2024-11-07 at 11 56 57 AM (2)](https://github.com/user-attachments/assets/960383a3-cc92-46c0-bd23-f92cf5c2414f)

2024-11-07 20:01 UTC, shawnkost requested changes
One change here Ally

2024-11-07 20:01 UTC, shawnkost commented on typescript-forms/form-events.ts
> +});
This is in the wrong file

2024-11-07 20:15 UTC, allygreven commented on typescript-forms/form-events.ts
> +});
oh shoot okay i'll change, thanks!

2024-11-14 17:23 UTC, shawnkost approved these changes
👍🏻

2024-11-15 02:45 UTC, merged