Completed Typescript and JSON Exercise-Allyson Greven
allygreven/c1024-code-solutions pull request #50
Opened 2024-11-09 00:18 UTC by allygreven

![Screenshot 2024-11-08 at 4 16 25 PM (2)](https://github.com/user-attachments/assets/c7d768ea-5e85-48f2-8dd8-c2ea455e07d4)

2024-11-11 17:01 UTC, shawnkost requested changes
Couple changes here Ally!

2024-11-11 17:01 UTC, shawnkost commented on typescript-and-json/main.ts
> +};
Is this an array or an object? This should be an array of objects

2024-11-11 17:01 UTC, shawnkost commented on typescript-and-json/main.ts
> +console.log('value of author:', typeof 'Frieda McFadden');
These should just be logging your array and the `typeof array`

2024-11-19 22:03 UTC, allygreven commented
![Screenshot 2024-11-19 at 1 57 39 PM (2)](https://github.com/user-attachments/assets/228720c1-fd25-4db5-8a33-d3ce190647e1)

2024-11-20 18:16 UTC, shawnkost approved these changes
👍🏻

2024-11-20 18:56 UTC, merged